### ISSUE TITLE
✨ [FEAT] ChatGPT API 요구사항 명세서 변경 사항 적용

### ISSUE THREAD

**Issue by alsrudursla** [IRECIPE/IRecipe-Server#56]
## 🔨 Describe
- 요구사항 명세서에 맞춰 ChatGPT API CRUD 를 변경합니다

## ✅ Tasks
- [x] 싫어하는 음식 입력받기
- [x] 재료 측정 방법 통일하기
- [x] 싫어하는 음식을 제외해서 레시피 추천하기
- [x] 필수 재료 & 선택 재료 구분해서 안내하기
